# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: latest
            - run: pnpm i --frozen-lockfile
            - run: pnpm run lint

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: latest

            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/

            - run: pnpm i --frozen-lockfile

            - name: Bump repo version and push tag to GitHub
              id: tag
              uses: anothrNick/github-tag-action@1.22.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  RELEASE_BRANCHES: master
                  DEFAULT_BUMP: patch

            - name: Bump npm version
              run: pnpm version ${{ steps.tag.outputs.tag }} --no-git-tag-version --allow-same-version

            - run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
